language: python
matrix:
    include:
        - name: "Python 2.6"
          dist: "trusty"
          python: "2.6"
        - name: "Python 2.7"
          dist: "trusty"
          python: "2.7"
        - name: "Python 3.2"
          python: "3.2"
          dist: "trusty"
        - name: "Python 3.3"
          python: "3.3"
          dist: "trusty"
        - name: "Python 3.4"
          python: "3.4"
        - name: "Python 3.5"
          python: "3.5"
        - name: "Python 3.6"
          python: "3.6"
        - name: "Python 3.7"
          python: "3.7"
addons:
    apt:
        packages:
            - enchant
install:
    - pip install -rtest-requirements.txt
    - pip install -e ./
script:
    - pycodestyle confpy/
    - pycodestyle tests/
    - pyflakes confpy/
    - pyflakes tests/
    - pylint --rcfile=.pylintrc confpy/
    - py.test tests/
